Map<String, String> tr = {
	"AF": "Afganistan",
	"AX": "Åland Adaları",
	"AL": "Arnavutluk",	
	"US": "Amerika Birleşik Devletleri",	
	"AS": "Amerikan Samoası",	
	"VI": "Amerikan Virjin Adaları",
	"AD": "Andorra",
	"AO": "Angola",
	"AI": "Anguilla",
	"AG": "Antigua ve Barbuda",
	"DE": "Almanya",
	"AR": "Arjantin",	
	"AW": "Aruba",
	"AC": "Ascension Adası",
	"AU": "Avustralya",
	"AT": "Avusturya",
	"AZ": "Azerbaycan",
	"BS": "Bahamalar",
	"BH": "Bahreyn",
	"BD": "Bangladeş",
	"BB": "Barbados",
	"EH": "Batı Sahra",
	"BY": "Beyaz Rusya",
	"BE": "Belçika",
	"BZ": "Belize",
	"BJ": "Benin",
	"BM": "Bermuda",
	"AE": "Birleşik Arap Emirlikleri",
	"BT": "Butan",
	"BO": "Bolivya",
	"BA": "Bosna Hersek",
	"BW": "Botsvana",
	"BR": "Brezilya",
	"VG": "Britanya Virjin Adaları",
	"BN": "Brunei",
	"BG": "Bulgaristan",
	"BF": "Burkina Faso",
	"BI": "Burundi",	
	"CV": "Cape Verde",	
	"GI": "Cebelitarık",
	"DZ": "Cezayir",	
	"KY": "Cayman Adaları",	
	"CX": "Christmas Adası",
	"DJ": "Cibuti",
	"CC": "Cocos [Keeling] Adaları",
	"CK": "Cook Adaları",
	"CW": "Curaçao",	
	"TD": "Çad",	
	"CZ": "Çek Cumhuriyeti",
	"CN": "Çin",				
	"DK": "Danimarka",	
	"CD": "Demokratik Kongo Cumhuriyeti",
	"DM": "Dominika",
	"DO": "Dominik Cumhuriyeti",	
	"TL": "Doğu Timor",
	"EC": "Ekvador",	
	"SV": "El Salvador",
	"ID": "Endonezya",
	"GQ": "Ekvator Ginesi",	
	"ER": "Eritre",
	"AM": "Ermenistan",
	"EE": "Estonya",
	"ET": "Etiyopya",
	"FK": "Falkland Adaları [Islas Malvinas]",
	"FO": "Faroe Adaları",
	"MA": "Fas",
	"FJ": "Fiji",
	"CI": "Fildişi Sahili",
	"PH": "Filipinler",
	"PS": "Filistin Toprakları",
	"FI": "Finlandiya",
	"FR": "Fransa",
	"GF": "Fransız Guyanası",
	"PF": "Fransız Polinezyası",
	"GA": "Gabon",
	"GM": "Gambiya",
	"GE": "Gürcistan",	
	"GH": "Gana",	
	"GL": "Grönland",
	"GD": "Grenada",
	"GP": "Guadeloupe",
	"GU": "Guam",
	"GT": "Guatemala",
	"GG": "Guernsey",
	"GN": "Gine Conakry",
	"GW": "Gine-Bissau",
	"GY": "Guyana",
	"ZA": "Güney Afrika",
	"GS": "Güney Georgia ve Güney Sandwich Adaları",
	"KR": "Güney Kore",
	"SS": "Güney Sudan",
	"HT": "Haiti",
	"HM": "Heard Adası ve McDonald Adaları",
	"HR": "Hırvatistan",
	"IN": "Hindistan",	
	"HN": "Honduras",
	"HK": "Hong Kong",			
	"NL": "Hollanda",
	"IQ": "Irak",
	"IO": "İngiliz Hint Okyanusu Bölgesi",
	"IR": "İran",	
	"GB": "İngiltere",
	"IE": "İrlanda",	
	"ES": "İspanya",	
	"IL": "İsrail",
	"SE": "İsveç",
	"CH": "İsviçre",
	"IT": "İtalya",
	"IS": "İzlanda",
	"JM": "Jamaika",
	"JP": "Japonya",
	"JE": "Jersey",
	"JO": "Ürdün",
	"KH": "Kamboçya",
	"CM": "Kamerun",
	"CA": "Kanada",
	"QA": "Katar",
	"ME": "Karadağ",
	"BQ": "Karayip Hollandası",	
	"KZ": "Kazakistan",
	"KE": "Kenya",	
	"KI": "Kiribati",
	"KG": "Kırgızistan",
	"CY": "Kıbrıs",
	"CO": "Kolombiya",
	"KM": "Komorlar",
	"CG": "Kongo Cumhuriyeti",
	"CR": "Kosta Rika",
	"XK": "Kosova",		
	"KW": "Kuveyt",
	"KP": "Kuzey Kore",
	"MP": "Kuzey Mariana Adaları",
	"CU": "Küba",
	"LA": "Laos",
	"LV": "Letonya",
	"LB": "Lübnan",
	"LS": "Lesotho",
	"LR": "Liberya",
	"LY": "Libya",
	"LI": "Lihtenştayn",
	"LT": "Litvanya",
	"LU": "Lüksemburg",
	"HU": "Macaristan",
	"MO": "Makao",
	"MK": "Makedonya",
	"MG": "Madagaskar",
	"MW": "Malavi",
	"MY": "Malezya",
	"MV": "Maldivler",
	"ML": "Mali",
	"MT": "Malta",
	"IM": "Man Adası",
	"MH": "Marshall Adaları",
	"MQ": "Martinik",	
	"MU": "Mauritius",
	"YT": "Mayotte",
	"MX": "Meksika",
	"EG": "Mısır",
	"FM": "Mikronezya",
	"MN": "Moğolistan",
	"MD": "Moldova"	,
	"MC": "Monako",	
	"MR": "Moritanya",
	"MS": "Montserrat",	
	"MZ": "Mozambik",
	"MM": "Myanmar [Burma]",
	"NA": "Namibya",
	"NR": "Nauru",
	"NP": "Nepal",	
	"NI": "Nikaragua",
	"NE": "Nijer",
	"NG": "Nijerya",
	"NU": "Niue",
	"NF": "Norfolk Adası",	
	"NO": "Norveç",	
	"CF": "Orta Afrika Cumhuriyeti",
	"PK": "Pakistan",
	"PW": "Palau",	
	"PA": "Panama",
	"PG": "Papua Yeni Gine",
	"PY": "Paraguay",
	"PE": "Peru",
	"PL": "Polonya",
	"PT": "Portekiz",
	"PR": "Porto Riko",	
	"RE": "Réunion",
	"RO": "Romanya",
	"RU": "Rusya",
	"RW": "Ruanda",
	"BL": "Saint Barthélemy",
	"SH": "Saint Helena",
	"KN": "St. Kitts",
	"LC": "St. Lucia",
	"MF": "Saint Martin",
	"PM": "Saint Pierre ve Miquelon",
	"VC": "Saint Vincent",
	"WS": "Samoa",
	"SM": "San Marino",
	"ST": "São Tomé ve Príncipe",
	"SA": "Suudi Arabistan",
	"SN": "Senegal",
	"RS": "Sırbistan",
	"SC": "Seyşeller",
	"SL": "Sierra Leone",
	"SG": "Singapur",
	"SX": "Sint Maarten",
	"SK": "Slovakya",
	"SI": "Slovenya",
	"SB": "Solomon Adaları",
	"SO": "Somali",	
	"LK": "Sri Lanka",
	"SD": "Sudan",
	"SR": "Surinam",
	"SJ": "Svalbard ve Jan Mayen",
	"SZ": "Svaziland",		
	"SY": "Suriye",
	"CL": "Şili",
	"TW": "Tayvan",
	"TJ": "Tacikistan",
	"TZ": "Tanzanya",
	"TH": "Tayland",
	"TG": "Togo",
	"TK": "Tokelau",
	"TO": "Tonga",
	"TT": "Trinidad / Tobago",
	"TC": "Turks ve Caicos Adaları",
	"TV": "Tuvalu",
	"TN": "Tunus",
	"TR": "Türkiye",
	"TM": "Türkmenistan",	
	"OM": "Umman",
	"UG": "Uganda",
	"UA": "Ukrayna",	
	"UY": "Uruguay",
	"UZ": "Özbekistan",
	"VU": "Vanuatu",
	"VA": "Vatikan Şehri",
	"VE": "Venezuela",
	"VN": "Vietnam",	
	"WF": "Wallis ve Futuna",
	"NC": "Yeni Kaledonya",
	"NZ": "Yeni Zelanda",
	"YE": "Yemen",
	"GR": "Yunanistan",
	"ZM": "Zambiya",
	"ZW": "Zimbabve", 
	"search": "Ara",
};
